### ISSUE TITLE
trifocal relative pose from lines at points

### ISSUE THREAD

**Issue by h1063135843** [C-H-Chien/Homotopy-Continuation-Tracker-on-GPU#2]
The chicago and cleveland problem in original parper of TRPLP both have 14 unknowns. Why is 30 unknows here? How could I compute those parameters from points and line correspondences in image pixels? If I only change the input of a specifc problem, not construct the problem from begining, is it enough to implement only the step 3.3 in Solve_New_Problems.md( prepare your target parameters for which the formulation is identical to the start parameters). Thanks a Lot.

**Comment by C-H-Chien** [comment]
Hi, thanks for the interest in GPU-HC.

You are right that in the TRPLP paper the problems have only 14 unknowns (two relative pose where rotation is parameterized by quaternions). This is because they reduce the 30x30 system into 14x14 in order to increase the efficiency of solving the problem (which however is still too slow to be practical). Refer to Corollary 2.3 of [the paper](https://ieeexplore.ieee.org/abstract/document/9969132) where the original problem size is 30x30. In GPU-HC, we stay in its native form (30x30) because _(i)_ the degree of the polynomial is lower than 14x14, meaning that the numerical accuracy is more stable in 30x30, and _(ii)_ the maximal number of monomials per polynomial equation in 30x30 (12) is way lesser than 14x14 (>240), so the 30x30 formulation is much simpler.

To get the parameters from points and line correspondences (actually it should be oriented-point correspondences, _i.e._, a point endowed with an orientation), please see [this Julia code](https://github.com/C-H-Chien/Homotopy-Continuation-Tracker-on-GPU/blob/main/start-sys-gen/trifocal_2op1p_30x30_monodromySolve.jl), where x is the point position while d is its associated tangent. Both are in metrics. 

If you are using GPU-HC, you will need to generate the indices of the problem Jacobian matrix (step 2.2: Create dH/dx, dH/dt, and H Evaluation Indices) in order to evaluate Jacobian matrices on the GPU side. So basically you cannot just jump to step 3.3 unless you are not going to use GPU-HC. 

If you need any assistance in solving your problem using GPU-HC, please feel free to let me know. I am happy to help!

p.s. A BMVC 2024 paper is going to be published where 30x30 trifocal pose estimation is used. I will share the paper link to you once it is available.

**Comment by h1063135843** [comment]
Thanks for your quick reply.

I am very glad to read the BMVC paper once it is available. In my case, I want to do some tests on the calibrated trinocular relative pose estimation problem with matched point and line features.

For chicago problem, there exists a implementation namely trifocal_2op1p_30x30. It is not a "new" problem, except step 3.3, step 2,2 is also needed. Does it means  dH/dx, dH/dt relates to the target parameters? And I have to complie auto generated cu file with different input parameters again and again. It seems not friendly for ransac.

Instead of chicago problem, I am more concerned about the cleveland problem, as I used learned point feature such as superpoint without orientation info. For the user adding a new problem in GPU-HC, the key steps are writing **auto-data-gen-tools/sys_*.m** and **sys-gen/<problem_name>_monodromySolve.jl**. The former is much difficult for me, expanding the polynomial equations mannually too hard and prone to make a mistake. Do you have a more convenient suggestion?

**Comment by C-H-Chien** [comment]
You are right that trifocal_2op1p_30x30 is not a new problem, but this is the first time that the 30x30 formulation is solved directly without reducing it to a smaller size problem (14x14).

> Does it means dH/dx, dH/dt relates to the target parameters? And I have to complie auto generated cu file with different input parameters again and again. It seems not friendly for ransac.

No, indices for evaluating dH/dx and dH/dt only needs to be done one time. If you have new target parameters, there is nothing you need to change for the GPU-HC solver. I guess there is some misunderstanding here: all the steps in `Solve_New_Problems.md` are done in the _pre-processing_ stage. When you have a new set of target parameters, you probably need to read another `target_params.txt` file (one example is [here]([target_params.txt](https://github.com/C-H-Chien/Homotopy-Continuation-Tracker-on-GPU/blob/main/GPU-HC/problems/trifocal_2op1p_30x30/target_params.txt)) and that's it. No auto generation is required.
However, the BMVC paper that it is going to be available has GPU-HC solving trifocal pose estimation with an embedded RANSAC scheme. The code will be released and will be shared soon.

> The former is much difficult for me, expanding the polynomial equations mannually too hard and prone to make a mistake. Do you have a more convenient suggestion?

I typically use Julia to construct the problem just like [trifocal_2op1p_30x30_monodromySolve.jl](https://github.com/C-H-Chien/Homotopy-Continuation-Tracker-on-GPU/blob/main/start-sys-gen/trifocal_2op1p_30x30_monodromySolve.jl), where expanding the polynomial system can be done easily. Another highly recommended approach is to stay with the native form of the Chicago or Cleveland format so that the polynomial equations are not that "big" and "complicated" (like I said, 30x30 has only 12 monomials per polynomial with degree 3 while 14x14 has >240 monomials per polynomial with degree 5).

**Comment by h1063135843** [comment]
Thanks, everything is clear. While waiting for the BMVC code release, I will try gpu-hc by myself first.

**Comment by C-H-Chien** [comment]
Thank you! I expect the code for that BMVC paper be released by the end of this week or early next week.

**Comment by C-H-Chien** [comment]
Hi! I apologize for being late on releasing the code of the BMVC paper as we are also using it for another paper which is now accepted by IPDPS 2025. Here is the link to the repository:
https://github.com/C-H-Chien/Trifocal_Pose_Estimation_using_Improved_GPUHC
Let me know if you have any questions. Thank you for your interest and kind consideration.
